In [287]:
import pandas as pd
import numpy as np

In [288]:
df = pd.read_csv('kidney_disease.csv')
df.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [289]:
df.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                object
wc                 object
rc                 object
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object

In [290]:
#dropping the id coloum as it is unique value which should be removed
df.drop("id",axis=1,inplace=True)

#there are 3 features with numeric values with '' .these are having object types. so we need to convert thenm into numeric.



In [291]:
Convert_feature=['pcv','wc','rc']
for feature in Convert_feature:
    df[feature] = pd.to_numeric(df[feature],errors='coerce')

In [292]:
def diff_num_cat(df):
    numeric_feature=[col for col in df.columns if df[col].dtype!='object']
    categorial_feature=[col for col in df.columns if df[col].dtype=='object']
    return numeric_feature,categorial_feature

In [293]:
numeric_features,categorial_feature=diff_num_cat(df)

In [294]:
numeric_features

['age',
 'bp',
 'sg',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hemo',
 'pcv',
 'wc',
 'rc']

In [295]:
categorial_feature

['rbc',
 'pc',
 'pcc',
 'ba',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [296]:
for i in categorial_feature:
    print('{} has {} values \n'.format(i,df[i].unique()))
   
df.isnull().sum()

rbc has [nan 'normal' 'abnormal'] values 

pc has ['normal' 'abnormal' nan] values 

pcc has ['notpresent' 'present' nan] values 

ba has ['notpresent' 'present' nan] values 

htn has ['yes' 'no' nan] values 

dm has ['yes' 'no' ' yes' '\tno' '\tyes' nan] values 

cad has ['no' 'yes' '\tno' nan] values 

appet has ['good' 'poor' nan] values 

pe has ['no' 'yes' nan] values 

ane has ['no' 'yes' nan] values 

classification has ['ckd' 'ckd\t' 'notckd'] values 



age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                71
wc                106
rc                131
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [297]:
def impute_mode(feature):
    mode = df[feature].mode()[0]
    df[feature] = df[feature].fillna(mode)

for i in categorial_feature:
    impute_mode(i)
    
def impute_mean(feature):
    mean=df[feature].mean()
    df.loc[df[feature].isnull(), feature] = np.round(mean,0)

for j in numeric_features:
    impute_mean(j)
    
df.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [278]:
# df = df.dropna(axis=0)
# df.isnull().sum()

In [299]:
df['rbc'] = df.rbc.replace(['normal','abnormal'], [1, 0])
df['pc'] = df.pc.replace(['normal','abnormal'], [1, 0])
df['pcc'] = df.pcc.replace(['present','notpresent'], [1, 0])
df['ba'] = df.ba.replace(['present','notpresent'], [1, 0])
df['htn'] = df.htn.replace(['yes','no'], [1, 0])
df['dm'] = df.dm.replace(['yes','no','\tyes','\tno',' yes' ], [1, 0,1,0,1])
df['cad'] = df.cad.replace(['yes','no','\tno'], [1, 0,0])
df['appet'] = df.appet.replace(['good','poor'], [1, 0])
df['pe'] = df.pe.replace(['yes','no'], [1, 0])
df['ane'] = df.ane.replace(['yes','no'], [1, 0])
df['classification'] = df.classification.replace(['ckd','ckd\t','notckd'], [1, 1,0])
df

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.0  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      1   0    0               1  
1    5.0    0   0    0      1   0    0               1  
2    5.0    0   1    0      0   0    1               1  
3    3.9    1   0    0      0   1    1               1  
4    4.6    0   0    0      1   0    0               1  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      1   0    0               0  
396  6.2    0   0    0      1   0    0               0  
397  5.4    0   0    0      1   0    0               0  
398  5.9    0   0    0      1   0    0               0  
399  6.1    0   0    0      1   0    0               0  

[400 rows x 25 columns]

In [300]:
df.drop_duplicates()

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...   pcv      wc  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  ...  44.0  7800.0   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.0  ...  38.0  6000.0   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  ...  31.0  7500.0   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  ...  32.0  6700.0   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  ...  35.0  7300.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...     ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.0  ...  47.0  6700.0   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.0  ...  54.0  7800.0   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.0  ...  49.0  6600.0   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.0  ...  51.0  7200.0   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.0  ...  53.0  6800.0   

      rc  htn  dm  cad  appet  pe  ane  classification  
0    5.2    1   1    0      1   0    0               1  
1    5.0    0   0    0      1   0    0               1  
2    5.0    0   1    0      0   0    1               1  
3    3.9    1   0    0      0   1    1               1  
4    4.6    0   0    0      1   0    0               1  
..   ...  ...  ..  ...    ...  ..  ...             ...  
395  4.9    0   0    0      1   0    0               0  
396  6.2    0   0    0      1   0    0               0  
397  5.4    0   0    0      1   0    0               0  
398  5.9    0   0    0      1   0    0               0  
399  6.1    0   0    0      1   0    0               0  

[400 rows x 25 columns]

In [301]:
input_features=[col for col in df.columns if col!='classification']
X=df[input_features]
y=df['classification']
X

age    bp     sg   al   su  rbc  pc  pcc  ba    bgr  ...  hemo   pcv  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.0  ...  15.4  44.0   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.0  ...  11.3  38.0   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.0  ...   9.6  31.0   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.0  ...  11.2  32.0   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.0  ...  11.6  35.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..    ...  ...   ...   ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.0  ...  15.7  47.0   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.0  ...  16.5  54.0   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.0  ...  15.8  49.0   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.0  ...  14.2  51.0   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.0  ...  15.8  53.0   

         wc   rc  htn  dm  cad  appet  pe  ane  
0    7800.0  5.2    1   1    0      1   0    0  
1    6000.0  5.0    0   0    0      1   0    0  
2    7500.0  5.0    0   1    0      0   0    1  
3    6700.0  3.9    1   0    0      0   1    1  
4    7300.0  4.6    0   0    0      1   0    0  
..      ...  ...  ...  ..  ...    ...  ..  ...  
395  6700.0  4.9    0   0    0      1   0    0  
396  7800.0  6.2    0   0    0      1   0    0  
397  6600.0  5.4    0   0    0      1   0    0  
398  7200.0  5.9    0   0    0      1   0    0  
399  6800.0  6.1    0   0    0      1   0    0  

[400 rows x 24 columns]

In [302]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

KNN Algorithm

In [303]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

knn_variable = KNeighborsClassifier()
knn_variable.fit(X_train, y_train)

# accuracy score, confusion matrix and classification report of knn

knn_acc = accuracy_score(y_test, knn_variable.predict(X_test))

print(f"Training Accuracy of KNN is {accuracy_score(y_train, knn_variable.predict(X_train))}")
print(f"Test Accuracy of KNN is {knn_acc} \n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, knn_variable.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, knn_variable.predict(X_test))}")

Training Accuracy of KNN is 0.853125
Test Accuracy of KNN is 0.725 

Confusion Matrix :- 
[[25  3]
 [19 33]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.57      0.89      0.69        28
           1       0.92      0.63      0.75        52

    accuracy                           0.73        80
   macro avg       0.74      0.76      0.72        80
weighted avg       0.79      0.72      0.73        80



In [305]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

# accuracy score, confusion matrix and classification report of decision tree

dtc_acc = accuracy_score(y_test, dtc.predict(X_test))

print(f"Training Accuracy of Decision Tree Classifier is {accuracy_score(y_train, dtc.predict(X_train))}")
print(f"Test Accuracy of Decision Tree Classifier is {dtc_acc} \n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, dtc.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, dtc.predict(X_test))}")

Training Accuracy of Decision Tree Classifier is 1.0
Test Accuracy of Decision Tree Classifier is 0.9875 

Confusion Matrix :- 
[[28  0]
 [ 1 51]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       1.00      0.98      0.99        52

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80



In [306]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

svc_acc=accuracy_score(y_test,svclassifier.predict(X_test))

print(f"Training Accuracy of Decision Tree Classifier is {accuracy_score(y_train, svclassifier.predict(X_train))}")
print(f"Test Accuracy of Decision Tree Classifier is {svc_acc}\n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, svclassifier.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, svclassifier.predict(X_test))}")

Training Accuracy of Decision Tree Classifier is 0.98125
Test Accuracy of Decision Tree Classifier is 0.9625

Confusion Matrix :- 
[[27  1]
 [ 2 50]]

Classification Report :- 
               precision    recall  f1-score   support

           0       0.93      0.96      0.95        28
           1       0.98      0.96      0.97        52

    accuracy                           0.96        80
   macro avg       0.96      0.96      0.96        80
weighted avg       0.96      0.96      0.96        80

